# https://docs.helix-editor.com/languages.html

[[language]]
name = "python"
language-servers = [ "pyright", "ruff" ]

[language-server.pyright.config.python.analysis]
typeCheckingMode = "basic"

[language-server.ruff]
command = "ruff-lsp"

[language-server.ruff.config.settings]
args = ["--ignore", "E501"]

[language.formatter]
command = "black"
args = ["--line-length", "88", "--quiet", "-"]

# https://rust-analyzer.github.io/manual.html
[language-server.rust-analyzer.config.check]
command = "clippy"

[[language]]
name = "go"
auto-format = true
formatter = { command = "goimports" }

[[language]]
name = "elixir"
auto-format = true
formatter = { command = "mix", args = ["format", "-"] }

[[language]]
name = "yaml"

[language-server.yaml-language-server.config.yaml]
format = { enable = true }
validation = true

[language-server.yaml-language-server.config.yaml.schemas]
"https://raw.githubusercontent.com/ansible-community/schemas/main/f/ansible-tasks.json" = "roles/{tasks,handlers}/*.{yml,yaml}"

[[language]]
name = "bash"
auto-format = true
formatter = { command = "shfmt", args = ["-i", "2", "-ci"] }

